// controllers/exportController.js
const Itinerary = require('../models/Itinerary');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Export itinerary as PDF
 */
exports.exportItineraryPDF = async (req, res) => {
  try {
    const { id } = req.params;
    
    // Check if user is authenticated
    if (!req.user) {
      return res.status(401).json({ 
        success: false, 
        message: 'Authentication required to export itineraries' 
      });
    }
    
    // Get itinerary
    const itinerary = await Itinerary.findById(id)
      .populate('userId', 'username')
      .populate('cityId', 'name');
      
    if (!itinerary) {
      return res.status(404).json({ success: false, message: 'Itinerary not found' });
    }
    
    // Check if user owns this itinerary
    const isOwner = req.user._id.toString() === itinerary.userId?.toString();
    if (!isOwner && !itinerary.isPublic) {
      return res.status(403).json({ 
        success: false, 
        message: 'Not authorized to export this itinerary' 
      });
    }
    
    // Create PDF document
    const doc = new PDFDocument();
    
    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=itinerary-${itinerary._id}.pdf`);
    
    // Pipe PDF to response
    doc.pipe(res);
    
    // Add content to PDF
    doc.fontSize(20).text(`${itinerary.title}`, { align: 'center' });
    doc.moveDown();
    
    if (itinerary.cityId) {
      doc.fontSize(16).text(`Destination: ${itinerary.cityId.name}`);
    }
    
    if (itinerary.preferences && itinerary.preferences.startDate) {
      const startDate = new Date(itinerary.preferences.startDate);
      doc.text(`Start Date: ${startDate.toDateString()}`);
    }
    
    doc.moveDown();
    
    // Add days and activities
    itinerary.days.forEach(day => {
      doc.fontSize(14).text(`Day ${day.day} (${day.date ? new Date(day.date).toDateString() : ''})`);
      doc.moveDown();
      
      day.items.forEach(item => {
        doc.fontSize(12).text(`${item.time}: ${item.placeName || 'Activity'}`);
        if (item.note) {
          doc.fontSize(10).text(`Note: ${item.note}`);
        }
        if (item.duration) {
          doc.fontSize(10).text(`Duration: ${item.duration}`);
        }
        doc.moveDown();
      });
      
      doc.moveDown();
    });
    
    // Add footer
    doc.fontSize(10).text('Generated by City Explorer', { align: 'center' });
    
    // Finalize PDF
    doc.end();
  } catch (err) {
    console.error('Error exporting itinerary as PDF:', err);
    res.status(500).json({ success: false, message: 'Failed to export itinerary' });
  }
};

/**
 * Export itinerary as JSON
 */
exports.exportItineraryJSON = async (req, res) => {
  try {
    const { id } = req.params;
    
    // Check if user is authenticated
    if (!req.user) {
      return res.status(401).json({ 
        success: false, 
        message: 'Authentication required to export itineraries' 
      });
    }
    
    // Get itinerary
    const itinerary = await Itinerary.findById(id)
      .populate('userId', 'username')
      .populate('cityId', 'name');
      
    if (!itinerary) {
      return res.status(404).json({ success: false, message: 'Itinerary not found' });
    }
    
    // Check if user owns this itinerary
    const isOwner = req.user._id.toString() === itinerary.userId?.toString();
    if (!isOwner && !itinerary.isPublic) {
      return res.status(403).json({ 
        success: false, 
        message: 'Not authorized to export this itinerary' 
      });
    }
    
    // Set response headers for JSON download
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', `attachment; filename=itinerary-${itinerary._id}.json`);
    
    // Send JSON data
    res.json(itinerary);
  } catch (err) {
    console.error('Error exporting itinerary as JSON:', err);
    res.status(500).json({ success: false, message: 'Failed to export itinerary' });
  }
};

/**
 * Export itinerary to calendar (ICS format)
 */
exports.exportItineraryCalendar = async (req, res) => {
  try {
    const { id } = req.params;
    
    // Check if user is authenticated
    if (!req.user) {
      return res.status(401).json({ 
        success: false, 
        message: 'Authentication required to export itineraries' 
      });
    }
    
    // Get itinerary
    const itinerary = await Itinerary.findById(id)
      .populate('userId', 'username')
      .populate('cityId', 'name');
      
    if (!itinerary) {
      return res.status(404).json({ success: false, message: 'Itinerary not found' });
    }
    
    // Check if user owns this itinerary
    const isOwner = req.user._id.toString() === itinerary.userId?.toString();
    if (!isOwner && !itinerary.isPublic) {
      return res.status(403).json({ 
        success: false, 
        message: 'Not authorized to export this itinerary' 
      });
    }
    
    // Generate ICS content
    let icsContent = 'BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//City Explorer//EN\nCALSCALE:GREGORIAN\n';
    
    itinerary.days.forEach(day => {
      day.items.forEach(item => {
        if (item.time && day.date) {
          // Create a datetime string for the event
          const eventDate = new Date(day.date);
          const [hours, minutes] = item.time.split(':');
          eventDate.setHours(hours, minutes || 0);
          
          // Format dates for ICS
          const formatDate = (date) => {
            return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
          };
          
          icsContent += 'BEGIN:VEVENT\n';
          icsContent += `UID:${itinerary._id}-${day.day}-${item.time}@cityexplorer.com\n`;
          icsContent += `DTSTART:${formatDate(eventDate)}\n`;
          icsContent += `DTEND:${formatDate(new Date(eventDate.getTime() + 3600000))}\n`; // +1 hour
          icsContent += `SUMMARY:${item.placeName || 'Activity'}\n`;
          if (item.note) {
            icsContent += `DESCRIPTION:${item.note}\n`;
          }
          icsContent += 'END:VEVENT\n';
        }
      });
    });
    
    icsContent += 'END:VCALENDAR';
    
    // Set response headers for ICS download
    res.setHeader('Content-Type', 'text/calendar;charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename=itinerary-${itinerary._id}.ics`);
    
    // Send ICS data
    res.send(icsContent);
  } catch (err) {
    console.error('Error exporting itinerary to calendar:', err);
    res.status(500).json({ success: false, message: 'Failed to export itinerary' });
  }
};